### ISSUE TITLE
BigCommerce Storefront Playground GraphQL API Issues

### ISSUE THREAD

**Issue by MohamedRezq** [bigcommerce/docs#470]
I am writing to express my frustration and concern regarding persistent issues I've been experiencing while attempting to utilize the BigCommerce Storefront API. Despite following the proper procedures and guidelines, I am consistently encountering the following error message:

```
{
  "errors": [
    {
      "message": "Failed to fetch",
      "stack": "TypeError: Failed to fetch\n    at https://developer.bigcommerce.com/_next/static/chunks/pages/_app-342a680a87abce14.js:47:12935\n    at fetch (https://developer.bigcommerce.com/_next/static/chunks/pages/graphql-storefront/playground-4557297afb5c3ac3.js:1:13525)\n    at https://developer.bigcommerce.com/_next/static/chunks/46381-e9b575f0bf6d6d5c.js:1:6748\n    at Generator.next (<anonymous>)\n    at resume (https://developer.bigcommerce.com/_next/static/chunks/46381-e9b575f0bf6d6d5c.js:1:4771)\n    at https://developer.bigcommerce.com/_next/static/chunks/46381-e9b575f0bf6d6d5c.js:1:4717\n    at new Promise (<anonymous>)\n    at l.<computed>.o.<computed> [as next] (https://developer.bigcommerce.com/_next/static/chunks/46381-e9b575f0bf6d6d5c.js:1:4670)\n    at https://developer.bigcommerce.com/_next/static/chunks/46381-e9b575f0bf6d6d5c.js:33:934"
    }
  ]
}
```

**Details of the Issue**

- Environment:

API URL Used: https://electon.mybigcommerce.com/graphql (also tried the official API URL format)
Authorization: Correctly using the Bearer token provided via the Storefront API.
Tool Used: BigCommerce Storefront API Playground and Postman.

- Steps Taken:

Generated a new Storefront API token with appropriate permissions.
Verified the correctness of the API URL and headers.
Tested the queries in both the Playground and Postman environments.

**Comment by MohamedRezq** [comment]
Solved by trying another browser!
Probably some cached keys or tokens are disturbing in chrome with the GraphQL Playground for me.
